/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package albumestampas.app.sistema;

import albumestampas.app.App;
import albumestampas.app.ListaEquipos;
import albumestampas.app.ListaEstampas;
import albumestampas.bean.Equipo;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author TrexT
 */
public class PanelAlbum extends javax.swing.JPanel {

    private ListaEquipos contenido;
    private JPanel panelEstampas; 
    private JScrollPane scroll;
    /**
     * Creates new form PanelAlbum
     */
    public PanelAlbum() {
        initComponents();
        inicializarAlbum();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEquipo = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblCapitan = new javax.swing.JLabel();
        lblTecnico = new javax.swing.JLabel();
        lblVictorias = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        lblEquipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEquipo.setText("jLabel1");

        lblCodigo.setText("lblCodigo");

        lblCapitan.setText("jLabel3");

        lblTecnico.setText("jLabel4");

        lblVictorias.setText("jLabel5");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addGap(18, 18, 18)
                .addComponent(lblEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblVictorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(384, 384, 384))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btnRegresar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCodigo)
                                    .addComponent(lblTecnico))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCapitan)
                                    .addComponent(lblVictorias))))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        add(btnAnterior, java.awt.BorderLayout.LINE_START);

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        add(btnSiguiente, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VentanaPrincipal ventanaPrincipal = new VentanaPrincipal();
        ventanaPrincipal.mostrar();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        try {
            agregarContenido(contenido.obtenerSiguiente().getEquipo());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        try {
            agregarContenido(contenido.obtenerAnterior().getEquipo());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCapitan;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEquipo;
    private javax.swing.JLabel lblTecnico;
    private javax.swing.JLabel lblVictorias;
    // End of variables declaration//GEN-END:variables

    private void inicializarAlbum() {
        try {
            contenido = App.listaUsuarios.getActual().getUsuario().getListaEquipos();
            agregarContenido(contenido.getActual().getEquipo());
        } catch (Exception e) {
            System.err.print("error al cargar datos");
        }
    }
    
    private void agregarContenido(Equipo equipo){
        lblEquipo.setText(equipo.getNombre());
        lblTecnico.setText(equipo.getDirectorTecnico());
        lblCodigo.setText(equipo.getCodigoFIFA());
        lblVictorias.setText(Integer.toString(equipo.getMundialesGanados()));
        lblCapitan.setText(equipo.getCapitan());
        agregarEstampas(equipo.getListaEstampas());
    }
    
    private void agregarEstampas(ListaEstampas estampas){
//        try {
//            this.remove(panelEstampas);
//        } catch (Exception e) {
//        }
        panelEstampas = new JPanel();
        estampas.volverAlInicio();
        try {
            for (int i = 0; i < estampas.getTamaño(); i++) {
                panelEstampas.add(new PanelEstampa(estampas.getActual().getEstampa()));
                estampas.siguienteEstampa();
            }
            if (estampas.getTamaño() >= 9 ) {
                scroll = new JScrollPane(panelEstampas);
                this.add(scroll, BorderLayout.CENTER);
            }else{
                this.add(panelEstampas, BorderLayout.CENTER);
            }
//            this.revalidate();
//            this.repaint();
        } catch (Exception e) {
            System.err.println("error al cargar estampas");
        }
    }
}
