/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package albumestampas.app.sistema;

import albumestampas.app.App;
import albumestampas.app.ListaEstampasSinPegar;
import albumestampas.bean.Estampa;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author TrexT
 */
public class PanelEstampasSinPegar extends javax.swing.JPanel {
    private ListaEstampasSinPegar listaEstampasSinPegar; 
    private JPanel panelEstampa = new JPanel();;
    /**
     * Creates new form PanelEstampasSinPegar
     */
    public PanelEstampasSinPegar() {
        initComponents();
    }
    
    public PanelEstampasSinPegar(ListaEstampasSinPegar listaEstampasSinPegar) {
        try {
            initComponents();
            listaEstampasSinPegar.mostrar();
            this.listaEstampasSinPegar = listaEstampasSinPegar;
            mostrarEstampas(this.listaEstampasSinPegar.getActual().getEstampa());
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnPegar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        add(btnAnterior, java.awt.BorderLayout.LINE_START);

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        add(btnSiguiente, java.awt.BorderLayout.LINE_END);

        btnPegar.setText("Pegar");
        btnPegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegarActionPerformed(evt);
            }
        });
        add(btnPegar, java.awt.BorderLayout.PAGE_END);

        jLabel2.setText("jLabel2");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addGap(94, 94, 94)
                .addComponent(jLabel2)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnRegresar))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VentanaPrincipal ventanaPrincipal = new VentanaPrincipal();
        ventanaPrincipal.mostrar();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        try {
            panelEstampa.removeAll();
            mostrarEstampas(listaEstampasSinPegar.obtenerSiguiente().getEstampa());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        try {
            panelEstampa.removeAll();
            mostrarEstampas(listaEstampasSinPegar.obtenerAnterior().getEstampa());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegarActionPerformed
         try {
            if (App.listaUsuarios.pegarEstampa(listaEstampasSinPegar.getActual().getEstampa())) {
                System.out.println("estampa pegada");
            }else{
                JOptionPane.showMessageDialog(null, "Estampa pegada", "Estampa pegada", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnPegarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnPegar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void mostrarEstampas(Estampa estampa) {
        try {
            panelEstampa.add(new PanelEstampa(estampa,0));
            //lblTitulo.setText(estampa.getNombre());
            this.add(panelEstampa, BorderLayout.CENTER);
            this.revalidate();
            this.repaint();
        } catch (Exception e) {
            System.err.println("error al cargar estampa del sobre");
        }
    }
}
