/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package albumestampas.app.sistema;

import albumestampas.app.App;
import albumestampas.bean.Estampa;

/**
 *
 * @author TrexT
 */
public class PanelEstampa extends javax.swing.JPanel {
    /**
     * Creates new form panelEstampa
     */
    public PanelEstampa() {
        initComponents();
    }
    
    public PanelEstampa(Estampa estampa){
        initComponents();
        agregarContenidoEstampa(estampa);
    }
    //1 sobre- o ver Album
    public PanelEstampa(Estampa estampa, int tipo){
        initComponents();
        agregarContenidoEstampa(estampa, tipo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblPosicion = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblClub = new javax.swing.JLabel();

        lblNombre.setText("jLabel1");

        lblPosicion.setText("jLabel2");

        lblFecha.setText("jLabel3");

        lblClub.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblPosicion)
                    .addComponent(lblFecha)
                    .addComponent(lblClub))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPosicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClub)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblClub;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPosicion;
    // End of variables declaration//GEN-END:variables

    private void agregarContenidoEstampa(Estampa estampa) {
        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), Integer.toString(estampa.getNoEstampa())));
        if (estampa.isPegado()|| App.listaUsuarios.getActual().getUsuario().getTipo() == 1) {
            lblClub.setText(estampa.getClub());
            lblFecha.setText(estampa.getFechaDeNacimiento());
            lblPosicion.setText(estampa.getPosicion());
            lblNombre.setText(estampa.getNombre());
        }else{
            lblClub.setVisible(false);
            lblFecha.setVisible(false);
            lblPosicion.setVisible(false);
            lblNombre.setVisible(false);
        }
    }
    
    private void agregarContenidoEstampa(Estampa estampa, int Tipo) {
        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), Integer.toString(estampa.getNoEstampa())));
        lblClub.setText(estampa.getClub());
        lblFecha.setText(estampa.getFechaDeNacimiento());
        lblPosicion.setText(estampa.getPosicion());
        lblNombre.setText(estampa.getNombre());
    }
}
