/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package albumestampas.app.sistema;

import albumestampas.app.App;
import albumestampas.app.ListaSobreDorado;
import albumestampas.app.ListaSobreNormal;
import albumestampas.bean.Estampa;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author TrexT
 */
public class PanelSobre extends javax.swing.JPanel {
    private ListaSobreDorado listaSobreDorado;
    private ListaSobreNormal listaSobreNormal;
    private int tipo;
    private JPanel panelEstampa = new JPanel();;
    
    /**
     * Creates new form PanelSobre
     */
    public PanelSobre() {
        initComponents();
    }
    
    public PanelSobre(int tipo){
        initComponents();
        obtenerEstampas(tipo);
        this.tipo = tipo;
        if (tipo == 1) {
            btnAnterior.setVisible(false);
            btnPegar.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnPegar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        lblTitulo.setText("jLabel1");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(53, 53, 53)
                .addComponent(lblTitulo)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(jButton1))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        add(btnAnterior, java.awt.BorderLayout.LINE_START);

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        add(btnSiguiente, java.awt.BorderLayout.LINE_END);

        btnPegar.setText("Pegar");
        btnPegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegarActionPerformed(evt);
            }
        });
        add(btnPegar, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        try {
            panelEstampa.removeAll();
            switch(this.tipo){
                case 0:
                    mostrarEstampas(listaSobreNormal.obtenerSiguiente().getEstampa());
                break;
                case 1:
                    mostrarEstampas(listaSobreDorado.obtenerSiguiente().getEstampa());
                break;
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        try {
            panelEstampa.removeAll();
            mostrarEstampas(listaSobreNormal.obtenerAnterior().getEstampa());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaPrincipal ventanaPrincipal = new VentanaPrincipal();
        ventanaPrincipal.mostrar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegarActionPerformed
        try {
            //System.out.println("siguiente");
            //panelEstampa.removeAll();
            switch(this.tipo){
                case 0:
                    if (App.listaUsuarios.pegarEstampa(listaSobreNormal.getActual().getEstampa())) {
                        System.out.println("estampa pegada");
                    }else{
                        JOptionPane.showMessageDialog(null, "Estampa pegada", "Estampa pegada", JOptionPane.ERROR_MESSAGE);
                    }
                break;
                case 1:
                    if (App.listaUsuarios.pegarEstampa(listaSobreDorado.getActual().getEstampa())) {
                        System.out.println("estampa pegada");
                    }else{
                        JOptionPane.showMessageDialog(null, "Estampa pegada", "Estampa pegada", JOptionPane.ERROR_MESSAGE);
                    }
                break;
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnPegarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnPegar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

    private void obtenerEstampas(int tipo) {
        try {
            switch(tipo){
                case 0:
                    listaSobreNormal = new ListaSobreNormal();
                    for (int i = 0; i < 5; i++) {
                        listaSobreNormal.insertar(App.listaEstampas.obtenerEstampaSobre(tipo).getEstampa());
                    }
                    //listaSobreNormal.mostrar();
                    App.listaUsuarios.agregarEstampasObtenidas(listaSobreNormal);
                    mostrarEstampas(listaSobreNormal.getActual().getEstampa());
                    break;
                case 1:
                    listaSobreDorado = new ListaSobreDorado();
                    for (int i = 0; i < 5; i++) {
                        listaSobreDorado.insertar(App.listaEstampas.obtenerEstampaSobre(tipo).getEstampa());
                    }
                    //listaSobreDorado.mostrar();
                    App.listaUsuarios.agregarEstampasObtenidas(listaSobreDorado);
                    mostrarEstampas(listaSobreDorado.getActual().getEstampa());
                    break;
            }
        } catch (Exception e) {
            System.err.println("error");
            e.printStackTrace();
        }
    }

    private void mostrarEstampas(Estampa estampa) {
        try {
            panelEstampa.add(new PanelEstampa(estampa,0));
            lblTitulo.setText(estampa.getNombre());
            this.add(panelEstampa, BorderLayout.CENTER);
            this.revalidate();
            this.repaint();
        } catch (Exception e) {
            System.err.println("error al cargar estampa del sobre");
        }
    }
}
